project:
  type: website

website:
  title: "Rubik's cube analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
      - href: source.qmd
      - href: about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



