---
title: "Data Analysis"
editor: visual
---

```{r}
library(tidyverse)



data <- read.csv("solves.csv")
```

```{r graphic1}

data2 <- head(data, n = 10)


graphic1 <- ggplot(data2, mapping = aes(x=Person,y=Fastest.Solve ,fill=Country)) +
  geom_col()
graphic1+
  labs(title="Person and his/her Fastest.Slove",
       subtitle="3x3 average",
       x="Person",
       y="Fastest.solve"
       )


```

```{r graphic2}
data3 <- data %>%
  filter(Country == c("USA","Mexico" ,"Canada"))


graphic2 <- ggplot(data3,mapping = aes(x=Fastest.Solve,color = Country, fill = Country)) +
  geom_density(linewidth = 0.75, alpha = 0.007)

graphic2+
 labs(title="North America",
       subtitle="3x3 average",
       x="Fastest Solve",
       y="Frequency"
       )

```

```{r graplic3}

data4 <- data %>%
  filter(Country == c("Brazil","Argentina"))


graphic3<- ggplot(data4,mapping = aes(x=Fastest.Solve,color = Country, fill = Country)) +
  geom_density(linewidth = 0.75, alpha =0.007)

graphic3+
 labs(title="South America",
       subtitle="3x3 average",
       x="Fastest Solve",
       y="Frequency"
       )
```

```{r graphic4}
data5 <- data %>%
  filter(Country == c("Australia" ))



graphic4<- ggplot(data5,mapping = aes(x=Fastest.Solve,color = Country, fill = Country)) +
  geom_density(linewidth = 0.75, alpha = 0.007)

graphic4+
 labs(title="
Australia",
       subtitle="3x3 average",
       x="Fastest Solve",
       y="Frequency"
       )
```

```{r graphic5}
data6 <- data %>%
  filter(Country == c("China","Philippines","Taiwan" ))


graphic5<- ggplot(data6,mapping = aes(x=Fastest.Solve,color = Country, fill = Country)) +
  geom_density(linewidth = 0.75, alpha = 0.007)


graphic5+
 labs(title="
Asia",
       subtitle="3x3 average",
       x="Fastest Solve",
       y="Frequency"
       )
```

```{r graphic6}
data7 <- data %>%
  filter(Country == c( "Denmark","Netherlands","Poland"))



graphic6<- ggplot(data7,mapping = aes(x=Fastest.Solve,color = Country, fill = Country)) +
  geom_density(linewidth = 0.75, alpha = 0.007)

graphic6+
 labs(title="
",
       subtitle="3x3 average",
       x="Fastest Solve",
       y="Frequency"
       )
```



```{r graphic7}

data8<- data


graphic7 <- ggplot(data8, mapping = aes(x=Country,y=Fastest.Solve )) +
  geom_col()
graphic7+
  labs(title="Person and his/her Fastest.Slove",
       subtitle="3x3 average",
       x="Person",
       y="Fastest.solve"
       )


```

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(maps)

world <- map_data("world")
head(world)

##        long      lat group order region subregion
## 1 -69.89912 12.45200     1     1  Aruba      <NA>
## 2 -69.89571 12.42300     1     2  Aruba      <NA>
## 3 -69.94219 12.43853     1     3  Aruba      <NA>
## 4 -70.00415 12.50049     1     4  Aruba      <NA>
## 5 -70.06612 12.54697     1     5  Aruba      <NA>
## 6 -70.05088 12.59707     1     6  Aruba      <NA>

world <- map_data("world")
worldplot <- ggplot() +
  geom_polygon(data = world, aes(x=long, y = lat, group = group)) + 
  coord_fixed(1.3)

worldgovt <- read.csv("./world-govt.csv", header = TRUE)
worldgovt <- select(worldgovt, region = indicator, "HDI" = `human.development.index`, "CC" = ISO.Country.code)
head(worldgovt)

##              region   HDI  CC
## 1       Afghanistan 0.498 AFG
## 2           Albania 0.785 ALB
## 3           Algeria 0.754 DZA
## 4           Andorra 0.858 AND
## 5            Angola 0.581 AGO
## 6 Antigua & Barbuda 0.780 ATG

## Check for disagreements between the two datasets
diff <- setdiff(world$region, worldgovt$region)

## Clean the dataset accordingly
worldgovt <- worldgovt %>%
  ## Recode certain entries
  mutate(region = recode(str_trim(region), "United States" = "USA",
                            "United Kingdom" = "UK",
                            "Korea (Rep.)" = "South Korea",
                            "Congo (Dem. Rep.)" = "Democratic Republic of the Congo",
                            "Congo (Rep.)" = "Republic of Congo")) %>%
  ## Editing the "North Korea" entry is a little trickier for some reason
  mutate(region = case_when((CC == "PRK") ~ "North Korea",
                               TRUE ~ as.character(.$region)))

## Make the HDI numeric
worldgovt$HDI <- as.numeric(as.character(worldgovt$HDI))

worldSubset <- inner_join(world, worldgovt, by = "region")
head(worldSubset)

##       long      lat group order      region subregion   HDI  CC
## 1 74.89131 37.23164     2    12 Afghanistan      <NA> 0.498 AFG
## 2 74.84023 37.22505     2    13 Afghanistan      <NA> 0.498 AFG
## 3 74.76738 37.24917     2    14 Afghanistan      <NA> 0.498 AFG
## 4 74.73896 37.28564     2    15 Afghanistan      <NA> 0.498 AFG
## 5 74.72666 37.29072     2    16 Afghanistan      <NA> 0.498 AFG
## 6 74.66895 37.26670     2    17 Afghanistan      <NA> 0.498 AFG

## Let's ditch many of the unnecessary elements
plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)

worldHDI <- ggplot(data = worldSubset, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) +
  geom_polygon(aes(fill = HDI)) +
  scale_fill_distiller(palette ="RdBu", direction = -1) + # or direction=1
  ggtitle("Global Human Development Index (HDI)") +
  plain

worldHDI


```








